### ISSUE TITLE
Using private repo

### ISSUE THREAD

**Issue by TamKez** [victorgarric/pip_search#33]
Hi, I'm working with a private pip repo, that has a different format from pypi.
How can I configure the module to work with my private repo? 
Furthermore I would love to know if pip-search currently or in the future checks for dependencies 
Thanks!

**Comment by victorgarric** [comment]
Greetings,

Actually, the way _pip-search_ works is by parsing the website pypi.org. So technically, it won't work with a private repo but I guess you can code an alternate system using the data broadcasted by your server. 

Concerning the check for dependencies, _pip_search_ solely aims at giving a descriptions and version checking. The dependency checks and installations process is and always will be processed by _pip_. This package was only created because _pip_ failed at what I personally consider to be the basic of what it should do : being able to search packages with keywords through command lines.
