### ISSUE TITLE
How can I get versions of packages show up when I run pip_search?

### ISSUE THREAD

**Issue by dougli1sqrd** [victorgarric/pip_search#4]
I just installed pip_search and looking at the image in the readme docs I expected to see available versions in pypi for a python package.

However, when I actually use pip_search on a package I just get a description.

```
$ pip_search requests
-----------------------  --------------------------------------------------------------------------------------------------------------------------------------------
Name                     Description

requests                 Python HTTP for Humans.
... <etc>
```

Is there something I need to do to get versions in pip_search results also?

I'm using python 3.5.

Thanks!

**Comment by victorgarric** [comment]
Since version 0.0.7, pip_search use rich for displaying and shows the latest version.

Consider updating it : 
`pip install pip_search --upgrade`

To get all the available version of a given package, it is comon usage to ask for a nonsense version directly to pip so it would display the available versions. E.g :
`pip install pip_search==999`

Which gives : 

> ERROR: Could not find a version that satisfies the requirement pip_search==999 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7)

Best reagards,
